---

- hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: provider_name
      prompt: Enter a provider name
      private: false
    - name: resource_name
      prompt: Enter a resource name
      private: false
  vars:
    core_path: "../core-tf-templates"
    provider_path: "../providers/{{ provider_name }}/{{ resource_name }}"
    output_path: "{{ provider_path }}/output"
  tasks:
    - include_vars: "{{ provider_path }}/resource.yml"
    - file:
        path: "{{ output_path }}"
        state: directory
    - name: Generate Resource Template
      template:
        src: "{{ core_path }}/tf_resource.tf.j2"
        dest: "{{ output_path }}/resource.tf.j2"
    - name: Generate Resource Variables Template
      template:
        src: "{{ core_path }}/variables.yml.j2"
        dest: "{{ output_path }}/variables.yml"
    - file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ provider_path }}/variables.yml"
        - "{{ provider_path }}/resource.tf.j2"
